name: "EKS Kubernetes Action"
description: "Interacts with kubernetes clusters calling kubectl commands. Integrates support for AWS EKS. Forked update of ConsenSys/kubernetes-action"
branding:
  icon: 'anchor'  
  color: 'blue'
inputs:
  args:
    description: "Arguments of kubectl"
    required: true
outputs:
  result:
    description: "Output of the kubectl command run"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
